FROM python:3.8-slim

# Create dagster workspace
RUN mkdir -p /opt/dagster/dagster_home /opt/dagster/app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy dagster instance YAML to $DAGSTER_HOME
COPY dagster.yaml /opt/dagster/dagster_home/

# Copy app files
WORKDIR /opt/dagster/app
COPY workspace.yaml workspace.yaml
COPY repos.py repos.py

# Run
ENV DAGSTER_HOME=/opt/dagster/dagster_home/
EXPOSE 3000
ENTRYPOINT ["dagster-daemon", "run"]